steps:
#  - name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
#    args: ['-f', 'docker-compose.yaml', 'up', '-d', '--build']

  - name: 'gcr.io/$PROJECT_ID/go-hpa:latest'
    args: ['test', '-cover', '/go/src/go-hpa']

images: ['gcr.io/$PROJECT_ID/go-hpa:latest']
