version: '3'

services:

  go-hpa:
    build: .
    container_name: go-hpa
    entrypoint: "/go/bin/go-hpa"
    ports:
      - 8000:8000
    # tty: true
    # environment:
    #     - GOPATH=/go/src/
    # volumes:
#     - ./src:/go/
