apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: go-hpa

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-hpa
    spec:
      containers:
        - name: go-hpa
          image: efepimenta/go-hpa:latest
          command: ["/go/bin/go-hpa"]

          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "100m"
